name: ai_fitness_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  dart_jsonwebtoken:  ^2.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/welcomeImage.jpeg
